### ISSUE TITLE
ติดตั้งเสร็จแล้ว มันขาด fution อะไรบางอย่างอยู่ครับ

### ISSUE THREAD

**Issue by rungtawee** [jir4yu/JindaAds#1]
http://upic.me/i/26/thispoint.jpg

ตามรูปด้านบนครับ ผมต้องทำอย่างไรครับ

**Comment by jir4yu** [comment]
อันนี้เป็นส่วนแสดง slider ครับ ซึ่งหากต้องการให้โพสต์ไหนก็ตามนำรูป feature มาแสดงที่ส่วนนี้ต้องใส่ tag ให้บทความนั้นว่า "feature" ตามหัวข้อ Quick Start (https://github.com/jir4yu/JindaAds#quick-start) เลยครับ

**Comment by rungtawee** [comment]
ขอบคุณครับ ผมอ่านไม่ครบเองครับ

**Comment by jir4yu** [comment]
ยินดีครับ
