### ISSUE TITLE
ไม่ดึง title ของบทความมา ไปดึง title ของเว็บหลักมาแทน

### ISSUE THREAD

**Issue by rawat2543** [jir4yu/JindaAds#2]
ตรงส่วนนี้ไม่มีอะไรดึงมาเลยครับ title ก็ไม่ดึง title ของบทความมา ไปดึง title ของเว็บหลักมาแทน

        <title> </title>
   <meta name="description" content=""
   <meta name="keywords" content=""

**Comment by jir4yu** [comment]
ตอนนี้อัพเวอร์ชั่นใหม่ขึ้นไปแก้ไขแล้วครับ ลองโหลดหรือ pull ลงมาดูนะครับ
ขอบคุณครับ

**Comment by rawat2543** [comment]
ขอบคุณครับ
