### ISSUE TITLE
ผมจะทราบในส่วนตรงนี้ยังไงครับ post-excerpt

### ISSUE THREAD

**Issue by sorawitkub** [jir4yu/JindaAds#3]
ตรง post-excerpt จะเป็นคำบรรยายย่อ ผมจะสามารถแก้ไขให้คำยาวได้ยังไงครับ

iconv_substr(get_the_excerpt(),0,160,"UTF-8") ตรงนี้หรือป่าวครับ 160

**Comment by jir4yu** [comment]
ถูกต้องแล้วครับ แก้ในเลข 160 นั่นได้เลย

**Comment by sorawitkub** [comment]
ผมได้ลองแก้ดูแล้วครับมันไม่เปลี่ยน หรือว่าต้องโพสต์ใหม่ครับ เพราะมันตัดแล้วบันทึกลงฐานข้อมูลเกี่ยวไหมครับ

**Comment by jir4yu** [comment]
ไฟล์ view-list.php ใช่มั้ยครับ
ปรกติแล้วเปลี่ยนตัวเลขก็ใช้ได้เลยครับ ที่ยังไม่ขึ้นได้ใช้ plugin cache หรือ cdn ครอบไว้บ้างหรือเปล่าครับ

**Comment by jir4yu** [comment]
ตอนนี้อัพเวอร์ชั่นแก้ไขขึ้นไปให้แล้วครับ ลองโหลดเวอร์ชั่นล่าสุดดูนะครับ
