### ISSUE TITLE
การแสดงผล Responsive Adsense ขนาด 300*250 ใน iphone มันล้นขอบครับ

### ISSUE THREAD

**Issue by KaPonGZaYo** [jir4yu/JindaAds#5]
![11720548_581109135364557_1320222786_n](https://cloud.githubusercontent.com/assets/13168236/8502484/c04caeca-21da-11e5-9d80-8313cd960427.jpg)
มันเป็นแบบนี้ครับ  ล้นขอบขวาครับ  เครื่องผมที่เป็นแอนดรอยด์ไม่มีปัญหาครับ  ช่วยแก้ไข้ให้ทีครับ  ขอบคุณครับ

**Comment by jir4yu** [comment]
สวัสดีครับ
ตรงนี้ผมยังไม่แน่ใจว่าจะแก้การแสดงผลที่ ads ได้หรือเปล่านะครับ เพราะถ้าแก้ไปอาจจะผิด guideline ของ Google ได้ แต่เดี๋ยวจะลองหาวิธีดูครับ

ขอบคุณที่แจ้งเข้ามาครับ
