### ISSUE TITLE
หาโค๊ดกล่องคอมเม้นท์เฟสบุ๊คในส่วน <body> ไม่เจอครับ

### ISSUE THREAD

**Issue by KaPonGZaYo** [jir4yu/JindaAds#6]
พอดีผมจะแก้ไขให้สามารถลบคอมเม้นท์ในส่วนคอมเม้นท์เฟสบุ๊คในบทความได้อะครับ  แล้วมันหาโค๊ดคอมเม้นท์ในส่วนของ <body> ไม่เจอ  เจอแต่ในไฟล์ single.php ที่ทำให้มันแสดงเฉยๆอะครับ  ไม่ทราบว่ามันอยู่ตรงไหนครับ  ขอบคุณครับ

**Comment by jir4yu** [comment]
ไม่ค่อยเข้าใจคำถามครับ 
หาอะไรในส่วนไหนไม่เจอนะครับ

**Comment by KaPonGZaYo** [comment]
คือ  ผมอยากที่จะจัดการกล่องคอมเม้นท์เฟสบุ๊คในเว็บได้อะครับ
 เช่นลบโพสความคิดเห็นอะไรประมาณนี้อะครับ

เมื่อ 5 กรกฎาคม 2558 10:21, Jirayu L <notifications@github.com> เขียนว่า:

**Comment by jir4yu** [comment]
ก่อนอื่นต้องเป็น moderator ของ app บน facebook นั้นก่อนครับ
ถ้าเป็น mod ของ app แล้วให้เข้า https://developers.facebook.com/tools/comments/ เพื่อจัดการความเห็นครับผม

**Comment by KaPonGZaYo** [comment]
แบบนี้ถูกมั้ยครับ  คือผมทำแบบนี้อะครับ  แต่มันยังไม่ได้ครับ
 มันไม่มีคอมเม้นท์เข้ามาในตัว App เลยอะครับ

เมื่อ 6 กรกฎาคม 2558 13:28, Jirayu L <notifications@github.com> เขียนว่า:
